name: CI Tests

on:
  push:
    branches:
    - 'develop/**'

  workflow_dispatch:
  pull_request:
    - master

jobs:

  unit-tests:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test

  code-review:
    - name: Coverage
    uses: codecov/codecov-action@v4.0.1
    env:
      token: ${{ secrets.CODECOV_TOKEN }}
      slug: kevi0x6e/nodejs-vulnerable

  deploy-test:
    needs: unit-tests
    if: github.ref == 'refs/heads/develop/**'

    runs-on: ubuntu-20.04
    concurrency: deploy-to-test
    environment: test

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: docker build -t setup-nodejs .
      - run: echo "Deploy"

  deploy-production:
    needs: test-ci
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-20.04
    concurrency: deploy-to-production
    environment: production

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: docker build -t setup-nodejs .
      - run: echo "Deploy"