name: CI Tests

on:
  push:
    branches:
      - develop/**
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:

  unit-tests:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test

  code-review:
    runs-on: ubuntu-20.04
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - run: npm ci

      - name: Run ESLint
        run: npx eslint .
        continue-on-error: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

      - name: Run ESLint with coverage
        run: npm run lint:coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy-test:
    needs: [unit-tests, code-review]
    if: startsWith(github.ref, 'refs/heads/develop/')

    runs-on: ubuntu-20.04
    concurrency: deploy-to-test
    environment: test

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: docker build -t setup-nodejs .
      - run: echo "Deploy"

  deploy-production:
    needs: [unit-tests, code-review]
    if: startsWith(github.ref, 'refs/heads/master')

    runs-on: ubuntu-20.04
    concurrency: deploy-to-production
    environment: production

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: docker build -t setup-nodejs .
      - run: echo "Deploy"